export const ACTIONS = {
    LOADING: 'LOADING',
    SELECT_CELL: 'SELECT_CELL',
    CLEAR_SELECTION: 'CLEAR_SELECTION',
    VALIDATE_WORD: 'VALIDATE_WORD',
    START_SELECTION: 'START_SELECTION',
    EXTEND_SELECTION: 'EXTEND_SELECTION',
    END_SELECTION: 'END_SELECTION',
    NEW_GAME: 'NEW_GAME',
    RESET_GAME: 'RESET_GAME',
    READY_GAME: 'READY_GAME',
    FINISH_GAME: 'FINISH_GAME',
    NEED_HELP: 'NEED_HELP',
    START_TIMER: 'START_TIMER',
    TICK: 'TICK',
} as const;

export type ActionType = (typeof ACTIONS)[keyof typeof ACTIONS];
